// ═══════════════════════════════════════════════════════════════
// PRESET PLAYLISTS - Curated 1-Click Game Packs
// ═══════════════════════════════════════════════════════════════

export const PRESET_PACKS = [
  {
    id: 'rock-nacional',
    name: 'Rock Nacional Clásico',
    genre: 'Rock Argentino',
    badge: '10 canciones',
    color: '#4F46E5',
    colorLight: '#EEF2FF',
    colorBorder: '#C7D2FE',
    description: 'Los himnos indiscutidos del rock argentino que todo el mundo sabe de memoria.',
    tracks: [
      { id: 'pre_rn_1', title: 'De Música Ligera', artist: 'Soda Stereo', type: 'youtube', url: 'https://www.youtube.com/watch?v=OX-us7PEfkc' },
      { id: 'pre_rn_2', title: 'El Amor Después del Amor', artist: 'Fito Páez', type: 'youtube', url: 'https://www.youtube.com/watch?v=F0p78Q4L4dE' },
      { id: 'pre_rn_3', title: 'Mil Horas', artist: 'Los Abuelos de la Nada', type: 'youtube', url: 'https://www.youtube.com/watch?v=f2nNfS7WwVw' },
      { id: 'pre_rn_4', title: 'Ji Ji Ji', artist: 'Patricio Rey y sus Redonditos de Ricota', type: 'youtube', url: 'https://www.youtube.com/watch?v=0h5oVf7u1qM' },
      { id: 'pre_rn_5', title: 'Flaca', artist: 'Andrés Calamaro', type: 'youtube', url: 'https://www.youtube.com/watch?v=UCF9oHCmB0M' },
      { id: 'pre_rn_6', title: 'Lamento Boliviano', artist: 'Los Enanitos Verdes', type: 'youtube', url: 'https://www.youtube.com/watch?v=B7bV3bT9y-Q' },
      { id: 'pre_rn_7', title: 'Rezo por Vos', artist: 'Charly García & Luis Alberto Spinetta', type: 'youtube', url: 'https://www.youtube.com/watch?v=yW6bU6JpWZQ' },
      { id: 'pre_rn_8', title: 'Spaghetti del Rock', artist: 'Divididos', type: 'youtube', url: 'https://www.youtube.com/watch?v=9_tM_u4U4C0' },
      { id: 'pre_rn_9', title: 'Pupilas Lejanas', artist: 'Los Pericos', type: 'youtube', url: 'https://www.youtube.com/watch?v=q6g4fDfqvA8' },
      { id: 'pre_rn_10', title: 'Irresponsables', artist: 'Babasónicos', type: 'youtube', url: 'https://www.youtube.com/watch?v=3-M9o1A_7U4' },
    ],
  },
  {
    id: 'cumbia-cuarteto',
    name: 'Cumbias & Cuarteto de Fiesta',
    genre: 'Cumbia & Cuarteto',
    badge: '10 canciones',
    color: '#FF5722',
    colorLight: '#FFF7ED',
    colorBorder: '#FFEDD5',
    description: 'Gilda, Rodrigo, Los Palmeras y los temas que levantan a todos de la silla.',
    tracks: [
      { id: 'pre_cc_1', title: 'No me arrepiento de este amor', artist: 'Gilda', type: 'youtube', url: 'https://www.youtube.com/watch?v=cM3k9fS2nO8' },
      { id: 'pre_cc_2', title: 'Soy Cordobés', artist: 'Rodrigo', type: 'youtube', url: 'https://www.youtube.com/watch?v=qE4cI6U7g3k' },
      { id: 'pre_cc_3', title: 'El Bombón Asesino', artist: 'Los Palmeras', type: 'youtube', url: 'https://www.youtube.com/watch?v=zJg5l1t1l40' },
      { id: 'pre_cc_4', title: 'Quién se ha tomado todo el vino', artist: 'La Mona Jiménez', type: 'youtube', url: 'https://www.youtube.com/watch?v=aG0dY3Q9wW4' },
      { id: 'pre_cc_5', title: 'Una Cerveza', artist: 'Ráfaga', type: 'youtube', url: 'https://www.youtube.com/watch?v=ZtK_g2mB1qQ' },
      { id: 'pre_cc_6', title: 'Yo me enamoré', artist: 'Amar Azul', type: 'youtube', url: 'https://www.youtube.com/watch?v=hN7mC3L9k7s' },
      { id: 'pre_cc_7', title: 'Nunca me faltes', artist: 'Antonio Ríos', type: 'youtube', url: 'https://www.youtube.com/watch?v=3WzW5fJ9kG8' },
      { id: 'pre_cc_8', title: 'Se me ha perdido un corazón', artist: 'Gilda', type: 'youtube', url: 'https://www.youtube.com/watch?v=9gWzF4j9L1s' },
      { id: 'pre_cc_9', title: 'La Mano de Dios', artist: 'Rodrigo', type: 'youtube', url: 'https://www.youtube.com/watch?v=Yf1eJ0o3f70' },
      { id: 'pre_cc_10', title: '17 Años', artist: 'Los Ángeles Azules', type: 'youtube', url: 'https://www.youtube.com/watch?v=3Y8a4w2qK9M' },
    ],
  },
  {
    id: 'pop-2000s',
    name: 'Hits Pop 2000s Bangerz',
    genre: 'Pop Internacional',
    badge: '10 canciones',
    color: '#D946EF',
    colorLight: '#FDF4FF',
    colorBorder: '#F5D0FE',
    description: 'Los himnos de discoteca y radio que marcaron a toda una generación.',
    tracks: [
      { id: 'pre_p2_1', title: '...Baby One More Time', artist: 'Britney Spears', type: 'youtube', url: 'https://www.youtube.com/watch?v=C-u5WLJ9Yk4' },
      { id: 'pre_p2_2', title: "Hips Don't Lie", artist: 'Shakira ft. Wyclef Jean', type: 'youtube', url: 'https://www.youtube.com/watch?v=DUT5rEU6pqM' },
      { id: 'pre_p2_3', title: 'I Gotta Feeling', artist: 'The Black Eyed Peas', type: 'youtube', url: 'https://www.youtube.com/watch?v=uSD4vsh1zDA' },
      { id: 'pre_p2_4', title: 'Without Me', artist: 'Eminem', type: 'youtube', url: 'https://www.youtube.com/watch?v=YVkUvmDQ3HY' },
      { id: 'pre_p2_5', title: 'Poker Face', artist: 'Lady Gaga', type: 'youtube', url: 'https://www.youtube.com/watch?v=bESGLojX874' },
      { id: 'pre_p2_6', title: 'Umbrella', artist: 'Rihanna ft. JAY-Z', type: 'youtube', url: 'https://www.youtube.com/watch?v=CvBfHwUxHIk' },
      { id: 'pre_p2_7', title: 'Hey Ya!', artist: 'Outkast', type: 'youtube', url: 'https://www.youtube.com/watch?v=PWgvGjAhvIw' },
      { id: 'pre_p2_8', title: 'Complicated', artist: 'Avril Lavigne', type: 'youtube', url: 'https://www.youtube.com/watch?v=5NPBIwQyPWE' },
      { id: 'pre_p2_9', title: 'Viva La Vida', artist: 'Coldplay', type: 'youtube', url: 'https://www.youtube.com/watch?v=dvgZkm1xWPE' },
      { id: 'pre_p2_10', title: 'Toxic', artist: 'Britney Spears', type: 'youtube', url: 'https://www.youtube.com/watch?v=LOZuxwVk7TU' },
    ],
  },
  {
    id: 'series-dibujitos',
    name: 'Intros de Series & Animé',
    genre: 'Nostalgia TV',
    badge: '10 canciones',
    color: '#059669',
    colorLight: '#ECFDF5',
    colorBorder: '#A7F3D0',
    description: 'Abrí el baúl de la infancia con las intros de tele más cantadas de la historia.',
    tracks: [
      { id: 'pre_sd_1', title: 'Cha-La Head-Cha-La', artist: 'Dragon Ball Z', type: 'youtube', url: 'https://www.youtube.com/watch?v=GHnfX1RmZX8' },
      { id: 'pre_sd_2', title: 'Atrápalos Ya (Tema de Apertura)', artist: 'Pokémon', type: 'youtube', url: 'https://www.youtube.com/watch?v=6xKWiCMKKJg' },
      { id: 'pre_sd_3', title: 'Tema de Apertura', artist: 'Los Simuladores', type: 'youtube', url: 'https://www.youtube.com/watch?v=vV1p2fB8nZ4' },
      { id: 'pre_sd_4', title: 'Apertura Instrumental', artist: 'Casados con Hijos', type: 'youtube', url: 'https://www.youtube.com/watch?v=b4b2W9p1a8s' },
      { id: 'pre_sd_5', title: "I'll Be There For You", artist: 'Friends (The Rembrandts)', type: 'youtube', url: 'https://www.youtube.com/watch?v=q-9kPks0IfE' },
      { id: 'pre_sd_6', title: 'The Simpsons Main Theme', artist: 'Los Simpsons (Danny Elfman)', type: 'youtube', url: 'https://www.youtube.com/watch?v=Xqog63mTHf8' },
      { id: 'pre_sd_7', title: 'Qué bonita vecindad', artist: 'El Chavo del 8', type: 'youtube', url: 'https://www.youtube.com/watch?v=oV8p3gB2a1s' },
      { id: 'pre_sd_8', title: 'Luz de Luna (Opening Latino)', artist: 'Sailor Moon', type: 'youtube', url: 'https://www.youtube.com/watch?v=W5hV9kG1b8s' },
      { id: 'pre_sd_9', title: 'We Are! (Opening Latino)', artist: 'One Piece', type: 'youtube', url: 'https://www.youtube.com/watch?v=HRaoEyRTr5o' },
      { id: 'pre_sd_10', title: 'Pegasus Fantasy', artist: 'Los Caballeros del Zodiaco', type: 'youtube', url: 'https://www.youtube.com/watch?v=rW5oG3a1s9p' },
    ],
  },
  {
    id: 'reggaeton-clasico',
    name: 'Reggaeton Old School',
    genre: 'Reggaeton Clásico',
    badge: '10 canciones',
    color: '#EA580C',
    colorLight: '#FFF7ED',
    colorBorder: '#FED7AA',
    description: 'Los temas que inauguraron el perreo en los boliches y fiestas de los 2000.',
    tracks: [
      { id: 'pre_rg_1', title: 'Gasolina', artist: 'Daddy Yankee', type: 'youtube', url: 'https://www.youtube.com/watch?v=CCF1_jI8Prk' },
      { id: 'pre_rg_2', title: 'Dale Don Dale', artist: 'Don Omar', type: 'youtube', url: 'https://www.youtube.com/watch?v=t5J5s2e9Z8k' },
      { id: 'pre_rg_3', title: 'Rakata', artist: 'Wisin & Yandel', type: 'youtube', url: 'https://www.youtube.com/watch?v=Zf0W6vP8g1s' },
      { id: 'pre_rg_4', title: 'Atrévete-te-te', artist: 'Calle 13', type: 'youtube', url: 'https://www.youtube.com/watch?v=vXtJkDHEAAc' },
      { id: 'pre_rg_5', title: 'Mayor Que Yo', artist: 'Baby Ranks, Daddy Yankee, Wisin & Yandel', type: 'youtube', url: 'https://www.youtube.com/watch?v=Z4b2c1N9m8k' },
      { id: 'pre_rg_6', title: "Pa' que retozen", artist: 'Tego Calderón', type: 'youtube', url: 'https://www.youtube.com/watch?v=aG3j9W8b2vA' },
      { id: 'pre_rg_7', title: 'Yo voy', artist: 'Zion & Lennox ft. Daddy Yankee', type: 'youtube', url: 'https://www.youtube.com/watch?v=bV9p2W8m1kG' },
      { id: 'pre_rg_8', title: 'Lo que pasó, pasó', artist: 'Daddy Yankee', type: 'youtube', url: 'https://www.youtube.com/watch?v=2r1p8W6m1kA' },
      { id: 'pre_rg_9', title: 'Dile', artist: 'Don Omar', type: 'youtube', url: 'https://www.youtube.com/watch?v=cM3k9bS2nO8' },
      { id: 'pre_rg_10', title: "Salgo pa' la calle", artist: 'Daddy Yankee ft. Randy', type: 'youtube', url: 'https://www.youtube.com/watch?v=yW8b1p9M2kA' },
    ],
  },
];
